image: dlang2/ldc-ubuntu

stages:
- install_dependencies
- build
- test

install-deps:
       stage: install_dependencies
       script: sudo apt install libsdl2 libsdl2-dev libglfw3 libglfw3-dev

build-release:
       stage: build
       script: ci/build-release.sh
       artifacts:
               paths:
               - ddmg

build-trial:
        stage: build
        script: ci/build-trial.sh
        artifacts:
                paths:
                - trial/trial

unittests:
        script: ci/unittests.sh
        dependencies:
        - build-trial
