build-release:
       stage: build
       script: ci/build-release.sh

build-trial:
        stage: build
        script: ci/build-trial.sh
        artifacts:
                paths:
                - trial/trial

unittests:
        script: ci/unittests.sh
        dependencies:
        - build-trial
